-- Run this script in the Supabase SQL Editor to create all necessary tables

CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  category_id BIGINT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  bulk_low_stock_grams BIGINT NOT NULL DEFAULT 1000,
  wholesale_rate_per_kg_paise BIGINT NOT NULL DEFAULT 0,
  unit_type TEXT NOT NULL DEFAULT 'weight'
);

CREATE TABLE IF NOT EXISTS public.product_variants (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id BIGINT NOT NULL,
  label TEXT NOT NULL,
  weight_grams BIGINT NOT NULL,
  barcode TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  retail_low_stock_pcs BIGINT NOT NULL DEFAULT 5
);

CREATE TABLE IF NOT EXISTS public.bulk_stock (
  product_id BIGINT PRIMARY KEY,
  qty_grams BIGINT NOT NULL DEFAULT 0,
  avg_cost_per_kg REAL
);

CREATE TABLE IF NOT EXISTS public.retail_packet_stock (
  variant_id BIGINT PRIMARY KEY,
  qty_pcs BIGINT NOT NULL DEFAULT 0,
  avg_cost_per_pc REAL
);

CREATE TABLE IF NOT EXISTS public.price_menu_entries (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  variant_id BIGINT NOT NULL,
  retail_price_paise BIGINT NOT NULL,
  wholesale_price_paise BIGINT NOT NULL,
  effective_date TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.suppliers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  phone TEXT
);

CREATE TABLE IF NOT EXISTS public.customers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type TEXT NOT NULL,
  name TEXT NOT NULL,
  business_name TEXT,
  phone TEXT,
  address TEXT,
  gst_no TEXT,
  credit_balance_paise BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.bulk_arrivals (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id BIGINT NOT NULL,
  date TEXT NOT NULL,
  qty_grams BIGINT NOT NULL,
  cost_per_kg_paise BIGINT,
  total_amount_paise BIGINT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.bulk_adjustments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id BIGINT NOT NULL,
  date TEXT NOT NULL,
  qty_change_grams BIGINT NOT NULL,
  reason TEXT NOT NULL,
  notes TEXT,
  user_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.packing_runs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date TEXT NOT NULL,
  product_id BIGINT NOT NULL,
  bulk_used_grams BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.packing_run_lines (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  packing_run_id BIGINT NOT NULL,
  variant_id BIGINT NOT NULL,
  packets_count BIGINT NOT NULL,
  unit_cost_at_pack REAL
);

CREATE TABLE IF NOT EXISTS public.retail_adjustments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  variant_id BIGINT NOT NULL,
  date TEXT NOT NULL,
  qty_change_pcs BIGINT NOT NULL,
  reason TEXT NOT NULL,
  notes TEXT,
  user_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.price_history (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  target_type TEXT NOT NULL,
  target_id BIGINT NOT NULL,
  old_price_paise BIGINT NOT NULL,
  new_price_paise BIGINT NOT NULL,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.invoices (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  invoice_no TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  invoice_datetime TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  business_date TEXT NOT NULL,
  type TEXT NOT NULL,
  customer_id BIGINT,
  subtotal_paise BIGINT NOT NULL,
  discount_paise BIGINT NOT NULL DEFAULT 0,
  total_paise BIGINT NOT NULL,
  payment_mode TEXT NOT NULL,
  amount_paid_paise BIGINT NOT NULL,
  balance_due_paise BIGINT NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'active',
  user_id BIGINT NOT NULL,
  payment_split TEXT
);

CREATE TABLE IF NOT EXISTS public.invoice_lines (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  invoice_id BIGINT NOT NULL,
  item_type TEXT NOT NULL,
  variant_id BIGINT,
  product_id BIGINT,
  qty BIGINT NOT NULL,
  unit TEXT NOT NULL,
  unit_price_paise BIGINT NOT NULL,
  line_total_paise BIGINT NOT NULL,
  unit_cost_snapshot REAL,
  line_profit_paise BIGINT
);

CREATE TABLE IF NOT EXISTS public.invoice_datetime_edit_log (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  invoice_id BIGINT NOT NULL,
  old_datetime TIMESTAMPTZ NOT NULL,
  new_datetime TIMESTAMPTZ NOT NULL,
  edited_by BIGINT NOT NULL,
  edited_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.payments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  customer_id BIGINT NOT NULL,
  invoice_id BIGINT,
  date TEXT NOT NULL,
  amount_paise BIGINT NOT NULL,
  mode TEXT NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.purchase_entries (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  supplier_id BIGINT,
  date TEXT NOT NULL,
  item_name TEXT NOT NULL,
  qty BIGINT NOT NULL,
  amount_paise BIGINT NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.expenses (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date TEXT NOT NULL,
  category TEXT NOT NULL,
  amount_paise BIGINT NOT NULL,
  payment_mode TEXT NOT NULL DEFAULT 'cash',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.label_print_log (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date TEXT NOT NULL,
  variant_id BIGINT NOT NULL,
  qty BIGINT NOT NULL,
  price_printed_paise BIGINT NOT NULL,
  type TEXT NOT NULL,
  user_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  pin_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
